config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :posts, param: :uuid do
    collection do
      get :favorites
      get :autocomplete
    end
    resources :comments, only: [ :create, :destroy, :edit, :update ]
  end
  resources :favorites, only: %i[create destroy]
  resources :profiles
  root "tops#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  get "contact", to: "static_pages#contact"

  resources :maps, only: [ :index ]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-pink'>
  <div class='container'>
    <div class= "row justify-content-end">
      <div class="col-auto"><%= link_to "利用規約", "/terms", class: 'link-dark' %></div>
      <div class="col-auto"><%= link_to "プライバシーポリシー", "/privacy", class: 'link-dark' %></div>
      <div class="col-auto"><%= link_to "お問い合わせ", "/contact", class: 'link-dark' %></div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-pink'>
    <%= link_to "キッチンカー日記", root_path, class: 'header-title' %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>

        <%= link_to 'ホーム', root_path, class: 'link-underline link-underline-opacity-0 link-dark mx-3' %>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '掲示板', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to '掲示板一覧', posts_path, class: 'dropdown-item' %>
            <%= link_to '掲示板作成', new_post_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <% if current_user %>
            <%= link_to '#', class: 'nav-link dropdown-toggle', id: 'userDropdown', role: 'button', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } do %>
              <% if current_user.avatar.attached? %>
                <%= image_tag url_for(current_user.avatar), class: "rounded-circle", style: "width:40px; height:40px;" %>
              <% else %>
                <div class="rounded-circle bg-secondary d-inline-flex justify-content-center align-items-center" style="width:40px; height:40px;">
                  <i class="bi bi-person"></i>
                </div>
              <% end %>
            <% end %>

            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              <li><span class="dropdown-item"><%= current_user.name %></span></li>
              <li><%= link_to 'プロフィール', profile_path(current_user.id), class: 'dropdown-item' %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' %></li>
            </ul>
           <% else %>
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
           <% end %>
         </li>
      </ul>
    </div>
  </nav>
</header>