config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :posts, param: :uuid do
    collection do
      get :favorites
      get :autocomplete
    end
    resources :comments, only: [ :create, :destroy, :edit, :update ]
  end
  resources :favorites, only: %i[create destroy]
  resources :profiles
  root "tops#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  get "contact", to: "static_pages#contact"

  resources :maps, only: [ :index ]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_uuid, on: :create
  has_many_attached :images
  has_many :favorites, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy
  belongs_to :category
  validates :title, presence: true
  validates :kitchen_car_name, presence: true
  validates :body, length: { maximum: 500 }
  after_commit :optimize_images, on: :create

  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    column_names
  end

  def self.ransackable_associations(auth_object = nil)
    [ "category", "comments", "favorites", "images_attachments", "images_blobs", "post_tags", "tags", "user" ]
  end

  def to_param
    uuid
  end

  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def optimize_images
    images.each do |image|
      optimized = image.variant(
        resize_to_limit: [ 1200, 1200 ],
        format: :webp
      ).processed

      image.blob.update!(content_type: "image/webp")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).page(params[:page]).page(params[:page]).per(12)
  end

  def show
    @post = Post.find_by!(uuid: params[:uuid])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_names = params[:post][:tag_names]

    if @post.save
      if tag_names.present?
        tags = tag_names.split(",").reject(&:blank?).uniq
        create_or_update_post_tags(@post, tags)
      end
      redirect_to posts_path, notice: "投稿しました"
    else
      flash.now[:danger] = "投稿できませんでした"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    post = current_user.posts.find_by!(uuid: params[:uuid])
    post.destroy
    redirect_to posts_path, notice: "削除しました"
  end

  def edit
    @post = current_user.posts.find_by!(uuid: params[:uuid])
  end

  def update
    @post = current_user.posts.find_by!(uuid: params[:uuid])
    tag_names = params[:post][:tag_names]
    Rails.logger.info "DEBUG: params[:post][:images] = #{params[:post][:images].inspect}"

    if @post.update(post_params.except(:images))
      if params[:post][:images].present? && params[:post][:images].reject(&:blank?).any?
        @post.images.purge if @post.images.attached?
        @post.images.attach(params[:post][:images])
      end

      if tag_names.present?
        tags = tag_names.split(",").reject(&:blank?).uniq
        create_or_update_post_tags(@post, tags)
      end
      redirect_to posts_path, notice: "更新しました"
    else
      flash.now[:danger] = "更新できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def autocomplete
    @posts = Post.where("title like ?", "%#{params[:q]}%")
    render layout: false
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :place, :visited_at, :kitchen_car_name, :body, :star, :latitude, :longitude, images: [])
  end

  def create_or_update_post_tags(post, tags)
    post.post_tags.destroy_all
    begin
    tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      post.tags << tag
      rescue ActiveRecord::RecordInvalid
        false
      end
    end
  end
end

app/views/posts/_favorite.html.erb
<%= link_to favorites_path(post_id: post.id), data: { turbo_method: :post } do %>
  <i class="bi bi-heart"></i>
<% end %>

app/views/posts/_favorite_buttons.html.erb
<div class='ms-auto'>
  <% if current_user %>
    <% if current_user.favorite?(post) %>
      <%= render 'posts/unfavorite', { post: post } %>
    <% else %>
      <%= render 'posts/favorite', { post: post } %>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<p class="text-muted small mb-3">
  <span class="text-danger">*</span> は必須項目です
</p>
<%= form_with model: @post, local: true, multipart: true do |f| %>
    <div class="mb-3">
      <%= f.label :title do %>
        タイトル <span class="text-danger">*</span>
      <% end %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="row">
      <div class="col-md-3">
        <%= f.label :category do %>
          カテゴリー <span class="text-danger">*</span>
        <% end %>
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "選択してください" %>
      </div>

      <div class="col-md-6">
        <%= f.label :place, "場所" %>
        <%= f.text_field :place, class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= f.label :visited_at, "訪れた日時" %>
        <%= f.datetime_local_field :visited_at, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3">
      <%= f.label :title do %>
        キッチンカーの名前 <span class="text-danger">*</span>
      <% end %>
      <%= f.text_field :kitchen_car_name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :body, "本文" %>
      <%= f.text_area :body, class: "form-control", rows: "10" %>
    </div>

    <div class="form-group">
      <%= f.label :star, "評価" %>

      <!-- hidden field（選んだ星が入る）-->
      <%= f.hidden_field :star, id: "post_star" %>

      <!-- ここに星が表示される -->
      <div id="post_raty"></div>
    </div>

    <div class="mb-3">
      <%= f.label :images, "画像" %>
      <%= f.file_field :images, multiple: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :tags, "タグ" %>
      <%= f.text_field :tag_names, placeholder: "例）クレープ, 東京, スイーツ", class: "form-control", value: post.tags.map(&:name).join(",") %>
    </div>

    <%= f.hidden_field :latitude, id: "post_latitude" %>
    <%= f.hidden_field :longitude, id: "post_longitude" %>

    <p>マップ</p>
    <div id='map' class="form-map"></div>

    <div class="d-flex justify-content-end">
      <%= f.submit nil, class: "btn btn-primary mt-5" %>
    </div>
  <% end %>

  <script
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap"
  async
  defer>
</script>

app/views/posts/_post.html.erb
<div class="card h-100 w-100 m-3">
  <div class="card-body d-flex flex-column">

    <%# ---------- 画像 ---------- %>
    <div class="image-wrapper position-relative mb-3">
      <% if post.images.attached? %>
        <%= image_tag post.images.first, class: "post-card-image mb-3" %>
      <% else %>
        <%= image_tag "default.png", class: "post-card-image mb-3" %>
      <% end %>

      <div class="position-absolute top-0 end-0 mt-1 me-3">
        <%= render "posts/favorite_buttons", post: post %>
      </div>
    </div>

    <%# ---------- タイトル・本文 ---------- %>
    <div class="flex-grow-1">
      <h3><%= post.title %></h3>
      <div class="post-show-star" data-score="<%= post.star %>"></div>
      <p>キッチンカーの名前：<%= post.kitchen_car_name %></p>
      <p>投稿日：<%= l(post.created_at, format: :short) %></p>
      <p>投稿者：<%= post.user.name %></p>

      <% if post.tags.present? %>
        <div class="mb-3">
          <%= render "posts/tags", post: post %>
        </div>
      <% end %>
    </div>

    <%# ---------- 下部ボタン ---------- %>
    <div class="mt-auto">
      <div class="d-flex justify-content-between">
        <%= link_to "詳細を見る", post_path(post), class: "btn btn-primary" %>

        <% if current_user == post.user %>
          <div>
            <%= link_to "編集", edit_post_path(post), class: "btn btn-primary me-2" %>
            <%= link_to "削除", post_path(post), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_tags.html.erb
<% post.tags.each do |tag| %>
  <span class="badge text-bg-info"><%= tag.name %></span>
<% end %>

app/views/posts/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(post_id: post.id)), data: { turbo_method: :delete } do %>
  <i class="bi bi-heart-fill"></i>
<% end %>

app/views/posts/autocomplete.html.erb
<% @posts.each do |post| %>
  <li class="flex w-full items-center list-group-item text-sm py-2 px-3 hover:bg-amber-100" role="option" data-autocomplete-value="<%= post.id %>" data-autocomplete-label="<%= post.title %>">
    <%= post.title %>
  </li>
<% end %>
  

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1 class="text-center border-bottom mt-5">投稿編集</h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="d-flex align-items-center justify-content-around border-bottom m-5 ">
  <h1 class="mb-0">投稿一覧</h1>
  <%= link_to "新規作成", new_post_path(@post), class: "btn btn-primary me-2" %>
</div>

<div class="card m-5  shadow-sm rounded-3">
  <h2 class="text-center mt-4">検索</h2>
  <%= search_form_for @q do |f| %>

    <div class="d-flex gap-5 ">

      <!-- キーワード検索 -->
      <div class="m-4 ms-5 flex-grow-1">
        <div data-controller="autocomplete" data-autocomplete-url-value="<%= autocomplete_posts_path %>" role="combobox">
          <%= f.label :title_or_kitchen_car_name_or_body_or_place_or_tags_name_cont, "検索ワード", class: "form-label" %><br>
          <%= f.search_field :title_or_kitchen_car_name_or_body_or_place_or_tags_name_cont, class: "w-100", placeholder: "キーワードを入力...", data: { autocomplete_target: 'input' } %>
          <%= f.hidden_field :title, data: { autocomplete_target: 'hidden' } %>
          <ul class="list-group" data-autocomplete-target="results"></ul>
        </div>
      </div>

      <!-- カテゴリ選択 -->
      <div class="mt-4 flex-grow-1">
        <%= f.label :category_id_eq, "カテゴリーを選択する", class: "form-label" %><br>
        <%= f.collection_select :category_id_eq, Category.where.not(id: 0), :id, :name,
              { include_blank: "カテゴリーを選択" }, class: "w-100" %>
      </div>

      <!-- ボタン -->
      <div class="mt-5 me-3 flex-shrink-0">
        <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-end"> 
  <%= sort_link(@q, :created_at, "作成日", class: "m-2") %>
  <%= sort_link(@q, :star, "評価順", class: "m-2") %>
</div>

<div class="row g-3 posts-wrapper">
  <% @posts.each do |post| %>
    <div class="col-md-4 d-flex mb-3">
      <%= render post %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center mt-5">
  <%= paginate @posts, theme: 'bootstrap-5'%>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <% if @post.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h1 class="text-center border-bottom mt-5">新規投稿</h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="card mb-4 p-3">
    <div class="row justify-content-evenly">
      <div class="col-4 position-relative">
      <h3 class="card-title mt-3"><%= @post.title %></h3>
        <div class="post-show-star" 
             class="card-text"
             data-score="<%= @post.star.to_i %>">
        </div>
        <div class="mt-5">
          <% if @post.images.attached? %>
            <%= image_tag @post.images.first, class: "img-fluid mb-3" %>
          <% else %>
            <%= image_tag "default.png", class: "img-fluid" %>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <div class="card-body">
        <div class="position-absolute top-0 end-0 mt-2 me-3">
          <%= render "posts/favorite_buttons", post: @post %>
        </div>
        <p class="card-text"><strong>キッチンカー名：</strong><%= @post.kitchen_car_name %></p>
        <p class="card-text"><strong>カテゴリ：</strong><%= @post.category.name %></p>
        <p class="card-text"><strong>出店場所：</strong><%= @post.place %></p>
        <div id='map' class="show-map" data-lat="<%= @post.latitude %>" data-lng="<%= @post.longitude %>"></div>
        <p class="card-text"><strong>投稿内容：</strong><%= simple_format(@post.body) %></p>
        <% if @post.tags.present? %>
          <div class="mb-3">
            <%= render 'posts/tags', post: @post %>
          </div>
        <% end %>
        <p class="card-text"><strong>投稿日：</strong><%= l(@post.created_at, format: :long) %></p>
        <p class="card-text"><strong>投稿者：</strong><%= link_to @post.user.name, profile_path(@post.user_id) %></p>

        <% if current_user == @post.user %>
            <%= link_to "編集", edit_post_path(@post), class: "btn btn-primary me-2" %>
            <%= link_to "削除", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card p-3 mb-4">
  <div id="comments">
    <%= render @post.comments %>
  </div>

  <div id="comment-form" class="mt-3">
    <%= render 'comments/form', comment: Comment.new, post: @post %>
  </div>
</div>

<script
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap"
  async
  defer>
</script>